name: First Bash

on:
  push:
    branches: ["*"]

jobs:
  job1:
    # bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run bash command
        env:
          MY_SECRET: ${{secrets.MY_SECRET}}
        run: |
          echo $MY_SECRET
          echo 'hi'
          echo 'today'
          npm install
  job2:
    if: github.event.pull_request.merged == true #action trigger when false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run bash command
        run: |
          echo 'hi'
          echo 'today'
          npm install

  

  